### PR TITLE
removed protocol suffix to fix circus ssl insecure content warning

### PR DESCRIPTION
**Pull request by meitham**
Hello,

We serve circus-web behind nginx with ssl, the google-fonts are hardcoded to use http, which causes warning in browser that some content is insecure, removing that allow the brwoser to use either http or https based access to google fonts.

### CODE REVIEW

**Comment by meitham** [comment]
Added fixes for flake8, not sure how to force rerunning the tox test.

**Comment by Natim** [comment]
Just add a commit and test will rerun themselves

**Comment by Natim** [comment]
Apparently there is one more fix: circusweb/circushttpd.py:18:80: E501 line too long (103 > 79 characters)

**Comment by meitham** [comment]
my local flake8 file was set to 120 so I could not see this one.  I have fixed it now.

**Comment by meitham** [comment]
Any indication whether this will be merged?  And is there any date in mind for the next release?

Thanks
M

**Pull request merged**
